

export class Spraak {
    liste: any[];

    constructor() {
        this.liste = [
            { 'id': 1, 'spraak': 'Acholi' },
            { 'id': 2, 'spraak': 'Afar' },
            { 'id': 3, 'spraak': 'Akan' },
            { 'id': 4, 'spraak': 'Amo' },
            { 'id': 5, 'spraak': 'Albansk' },
            { 'id': 6, 'spraak': 'Amharisk' },
            { 'id': 7, 'spraak': 'Arabisk' },
            { 'id': 8, 'spraak': 'Arameisk' },
            { 'id': 9, 'spraak': 'Armensk' },
            { 'id': 10, 'spraak': 'Aserbadjansk' },
            { 'id': 11, 'spraak': 'Asyrisk' },
            { 'id': 12, 'spraak': 'Azari' },
            { 'id': 13, 'spraak': 'Kurdisk-Badini' },
            { 'id': 14, 'spraak': 'Baluchi' },
            { 'id': 15, 'spraak': 'Bambara' },
            { 'id': 16, 'spraak': 'Bengali' },
            { 'id': 17, 'spraak': 'Benin' },
            { 'id': 18, 'spraak': 'Berbisk' },
            { 'id': 19, 'spraak': 'Bete' },
            { 'id': 20, 'spraak': 'Bilen' },
            { 'id': 21, 'spraak': 'Bisaya' },
            { 'id': 22, 'spraak': 'Bosnisk' },
            { 'id': 23, 'spraak': 'Bulgarsk' },
            { 'id': 24, 'spraak': 'Burmesisk' },
            { 'id': 25, 'spraak': 'Cebuano' },
            { 'id': 26, 'spraak': 'Chao' },
            { 'id': 27, 'spraak': 'Zhou' },
            { 'id': 28, 'spraak': 'Chin' },
            { 'id': 29, 'spraak': 'Dansk' },
            { 'id': 30, 'spraak': 'Dari' },
            { 'id': 31, 'spraak': 'Diola' },
            { 'id': 32, 'spraak': 'Djerma' },
            { 'id': 33, 'spraak': 'Engelsk' },
            { 'id': 34, 'spraak': 'Engelsk-am.' },
            { 'id': 35, 'spraak': 'Estisk' },
            { 'id': 36, 'spraak': 'Ewe' },
            { 'id': 37, 'spraak': 'Farsi (persisk)' },
            { 'id': 38, 'spraak': 'Feili' },
            { 'id': 39, 'spraak': 'Filippinsk' },
            { 'id': 40, 'spraak': 'Finsk' },
            { 'id': 41, 'spraak': 'Flamsk' },
            { 'id': 42, 'spraak': 'Fransk' },
            { 'id': 43, 'spraak': 'Fula' },
            { 'id': 44, 'spraak': 'Færøyisk' },
            { 'id': 45, 'spraak': 'Gassisk' },
            { 'id': 46, 'spraak': 'Georgisk' },
            { 'id': 47, 'spraak': 'Gresk' },
            { 'id': 48, 'spraak': 'Hausa' },
            { 'id': 49, 'spraak': 'Hazaragi' },
            { 'id': 50, 'spraak': 'Hebraisk' },
            { 'id': 51, 'spraak': 'Hindi' },
            { 'id': 52, 'spraak': 'Hviterussisk' },
            { 'id': 53, 'spraak': 'Ibo' },
            { 'id': 54, 'spraak': 'Indonesisk' },
            { 'id': 55, 'spraak': 'Ingushetisk' },
            { 'id': 56, 'spraak': 'Islandsk' },
            { 'id': 57, 'spraak': 'Italiensk' },
            { 'id': 58, 'spraak': 'Japansk' },
            { 'id': 59, 'spraak': 'Kakwa' },
            { 'id': 60, 'spraak': 'Kamba' },
            { 'id': 61, 'spraak': 'Kantonesisk' },
            { 'id': 62, 'spraak': 'Karen' },
            { 'id': 63, 'spraak': 'Karenni' },
            { 'id': 64, 'spraak': 'Katalansk' },
            { 'id': 65, 'spraak': 'Kazak/Tatar' },
            { 'id': 66, 'spraak': 'Kazakhisk' },
            { 'id': 67, 'spraak': 'Khmer' },
            { 'id': 68, 'spraak': 'Kinesisk' },
            { 'id': 69, 'spraak': 'Kinyarwanda' },
            { 'id': 70, 'spraak': 'Kirundi' },
            { 'id': 71, 'spraak': 'Kiswahili' },
            { 'id': 72, 'spraak': 'Koreansk' },
            { 'id': 73, 'spraak': 'Krio (creol – english)' },
            { 'id': 74, 'spraak': 'Krio (creol)' },
            { 'id': 75, 'spraak': 'Kroatisk' },
            { 'id': 76, 'spraak': 'Kurdisk-Kurmancî' },
            { 'id': 77, 'spraak': 'Latin' },
            { 'id': 78, 'spraak': 'Latvisk' },
            { 'id': 79, 'spraak': 'Lingala' },
            { 'id': 80, 'spraak': 'Litauisk' },
            { 'id': 81, 'spraak': 'Luganda' },
            { 'id': 82, 'spraak': 'Luo' },
            { 'id': 83, 'spraak': 'Makedonsk' },
            { 'id': 84, 'spraak': 'Malay' },
            { 'id': 85, 'spraak': 'Mandarin' },
            { 'id': 86, 'spraak': 'Mandingo' },
            { 'id': 87, 'spraak': 'Mandinka' },
            { 'id': 88, 'spraak': 'Mende' },
            { 'id': 89, 'spraak': 'Moldovsk' },
            { 'id': 90, 'spraak': 'Mongolsk' },
            { 'id': 91, 'spraak': 'Nederlandsk' },
            { 'id': 92, 'spraak': 'Nepali' },
            { 'id': 93, 'spraak': 'Norsk' },
            { 'id': 94, 'spraak': 'Oromo' },
            { 'id': 95, 'spraak': 'Pashto' },
            { 'id': 96, 'spraak': 'Polsk' },
            { 'id': 97, 'spraak': 'Portugisisk' },
            { 'id': 98, 'spraak': 'Punjabi' },
            { 'id': 99, 'spraak': 'Rohingya' },
            { 'id': 100, 'spraak': 'Romanes' },
            { 'id': 101, 'spraak': 'Romani' },
            { 'id': 102, 'spraak': 'Rumensk' },
            { 'id': 103, 'spraak': 'Russisk' },
            { 'id': 104, 'spraak': 'Rwandisk' },
            { 'id': 105, 'spraak': 'Saho' },
            { 'id': 106, 'spraak': 'Samisk' },
            { 'id': 107, 'spraak': 'Serbisk' },
            { 'id': 108, 'spraak': 'Serbokroatisk' },
            { 'id': 109, 'spraak': 'Singalesisk' },
            { 'id': 110, 'spraak': 'Slovakisk' },
            { 'id': 111, 'spraak': 'Slovensk' },
            { 'id': 112, 'spraak': 'Somali' },
            { 'id': 113, 'spraak': 'Soninke' },
            { 'id': 114, 'spraak': 'Sorani' },
            { 'id': 115, 'spraak': 'Spansk' },
            { 'id': 116, 'spraak': 'Svensk' },
            { 'id': 117, 'spraak': 'Swahili' },
            { 'id': 118, 'spraak': 'Tadzhik' },
            { 'id': 119, 'spraak': 'Tagalog' },
            { 'id': 120, 'spraak': 'Tamil' },
            { 'id': 121, 'spraak': 'Thai' },
            { 'id': 122, 'spraak': 'TIBETANSK' },
            { 'id': 123, 'spraak': 'Tigre' },
            { 'id': 124, 'spraak': 'Tigrinja' },
            { 'id': 125, 'spraak': 'Tsjekkisk' },
            { 'id': 126, 'spraak': 'Tsjetsjensk' },
            { 'id': 127, 'spraak': 'Turkmensk' },
            { 'id': 128, 'spraak': 'Twi' },
            { 'id': 129, 'spraak': 'Tyrkisk' },
            { 'id': 130, 'spraak': 'Tysk' },
            { 'id': 131, 'spraak': 'Ukrainsk' },
            { 'id': 132, 'spraak': 'Ungarsk' },
            { 'id': 133, 'spraak': 'Urdu' },
            { 'id': 134, 'spraak': 'Uyghur' },
            { 'id': 135, 'spraak': 'Uzbekisk' },
            { 'id': 136, 'spraak': 'Vietnamesisk' },
            { 'id': 137, 'spraak': 'Visaya' },
            { 'id': 138, 'spraak': 'Wolof' },

        ];
    }

   
}
